- id: '1588440618312'
  alias: Umidità Dreizel
  description: ''
  trigger:
  - below: '15'
    entity_id: sensor.mi_m_80eaca88f922
    platform: numeric_state
  condition: []
  action:
  - data:
      filename: /tmp/snapshot.jpg
    entity_id: camera.onvif_camera
    service: camera.snapshot
  - data:
      message: 'Umidità Dreizel: {{ states(''sensor.mi_m_80eaca88f922'') }}%'
    service: telegram_bot.send_message
- id: '1588515028645'
  alias: Blackout
  description: ''
  trigger:
  - entity_id: binary_sensor.stato_ups_salotto
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: 'Stato linea elettrica: {{ states(''binary_sensor.stato_ups_salotto'')
        }}'
    service: telegram_bot.send_message
